annuaire-entreprises-data-gouv-fr/search-api

.github/workflows/linting.yml, .github/workflows/workflow.yml
=> Exécuter les tests unitaires dans la CI

aio/aio-proxy/aio_proxy/helper.py, aio/aio-proxy/aio_proxy/routes.py, aio/aio-proxy/aio_proxy/search/index.py
=> Cacher les champs de concaténation dans les résultas de l'API

.github/workflows/workflow.yml, aio/aio-proxy/aio_proxy/decorators.py, aio/aio-proxy/aio_proxy/decorators/http_exception.py, aio/aio-proxy/aio_proxy/decorators/http_exceptions.py, aio/aio-proxy/aio_proxy/decorators/value_exception.py, aio/aio-proxy/aio_proxy/helpers.py, aio/aio-proxy/aio_proxy/parameters.py, aio/aio-proxy/aio_proxy/parsers/activite_principale.py, aio/aio-proxy/aio_proxy/parsers/code_postal.py, aio/aio-proxy/aio_proxy/parsers/entrepreneur_individuel.py, aio/aio-proxy/aio_proxy/parsers/latitude.py, aio/aio-proxy/aio_proxy/parsers/longitude.py, aio/aio-proxy/aio_proxy/parsers/page.py, aio/aio-proxy/aio_proxy/parsers/per_page.py, aio/aio-proxy/aio_proxy/parsers/radius.py, aio/aio-proxy/aio_proxy/parsers/string_parser.py, aio/aio-proxy/aio_proxy/parsers/terms.py, aio/aio-proxy/aio_proxy/parsers/tranche_effectif.py, aio/aio-proxy/aio_proxy/response.py, aio/aio-proxy/aio_proxy/routes.py, aio/aio-proxy/aio_proxy/search/helpers.py, aio/aio-proxy/aio_proxy/search/search_functions.py, aio/aio-proxy/aio_proxy/tests/test_activite_principale.py, aio/aio-proxy/aio_proxy/tests/test_code_postal.py, aio/aio-proxy/aio_proxy/tests/test_entrepreneur_individuel.py, aio/aio-proxy/aio_proxy/tests/test_tranche_effectif.py
=> Ajouter la recherche géographique à l'API

aio/aio-proxy/aio_proxy/response/format_response.py, aio/aio-proxy/aio_proxy/response/helpers.py
=> Add helper function to format response fields

aio/aio-proxy/aio_proxy/parsers/page.py, aio/aio-proxy/aio_proxy/parsers/per_page.py, aio/aio-proxy/aio_proxy/response/build_response.py
=> Corriger nombre de pages affichées

aio/aio-proxy/aio_proxy/doc/open-api.yml
=> Ajouter un example de réponse à la documentation

aio/aio-proxy/aio_proxy/response/build_response.py, aio/aio-proxy/aio_proxy/search/index.py
related to https://github.com/etalab/annuaire-entreprises-search-infra/pull/43
=> refactor: rename elasticsearch index

aio/aio-proxy/aio_proxy/search/helpers.py, aio/aio-proxy/aio_proxy/search/search_functions.py
=> Match field names to index mapping

aio/aio-proxy/aio_proxy/response/parameters.py, aio/aio-proxy/aio_proxy/search/filters.py, aio/aio-proxy/aio_proxy/search/helpers.py, aio/aio-proxy/aio_proxy/search/search_functions.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_is_siren.py
=> Add siren filter

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/format_response.py, aio/aio-proxy/aio_proxy/response/parameters.py, aio/aio-proxy/aio_proxy/search/helpers.py, aio/aio-proxy/aio_proxy/search/search_functions.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_association.py
=> Ajouter le filtre "est_association"

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/parsers/bool_fields.py, aio/aio-proxy/aio_proxy/parsers/string_parser.py, aio/aio-proxy/aio_proxy/parsers/type_personne.py, aio/aio-proxy/aio_proxy/response/parameters.py, aio/aio-proxy/aio_proxy/search/search_functions.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_association.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_collectivite_territoriale.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_entrepreneur_individuel.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_entrepreneur_spectacle.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_finess.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_rge.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_type_personne.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_uai.py
=> Ajouter le filtre "type_personne"

aio/aio-proxy/aio_proxy/search/search_functions.py
=> Add 'liste élus' to search function

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/parsers/etat_administratif.py, aio/aio-proxy/aio_proxy/response/parameters.py
=> Ajouter le filtre d'état administratif

.github/workflows/workflow.yml, aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/parsers/ess.py, aio/aio-proxy/aio_proxy/response/parameters.py
=> Ajouter le filtre`est_ess` (economie sociale et solidaire)

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/helpers.py
Demande du support
closes #104
=> Ajouter `type dirigeant` au payload de l'API

.github/ISSUE_TEMPLATE/proposer-une-amélioration---.md
related to https://github.com/etalab/annuaire-entreprises-search-api/pull/118
Je me suis inspirée du template de data.gouv : https://github.com/etalab/data.gouv.fr/blob/main/.github/ISSUE_TEMPLATE/proposer-une-am-lioration.md
=> docs: create feature issue template

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/parsers/per_page.py
=> Limit number of results per page to 25

aio/aio-proxy/aio_proxy/search/text_search.py
Filter by dirigeant and élus not working due to a mistake in indentation.
=> fix: remove error indentation

aio/aio-proxy/aio_proxy/response/format_response.py, aio/aio-proxy/aio_proxy/search/execute_search.py
=> Fix le `total results` count quand l'option `collapse` est utilisée par Elasticsearch

aio/aio-proxy/aio_proxy/parsers/empty_params.py, aio/aio-proxy/aio_proxy/parsers/matching_size.py, aio/aio-proxy/aio_proxy/parsers/terms.py, aio/aio-proxy/aio_proxy/search/filters/nested_etablissements_filters.py, aio/aio-proxy/aio_proxy/search/geo_search.py, aio/aio-proxy/aio_proxy/search/parameters.py, aio/aio-proxy/aio_proxy/search/queries/text.py, aio/aio-proxy/aio_proxy/search/text_search.py
Add API parameter to specify size of `matching établissements` field (size of inner hits).
=> Ajouter paramètre pour préciser les nombre de `matching établissements`

aio/aio-proxy/aio_proxy/response/formatters/enseignes.py, aio/aio-proxy/aio_proxy/response/formatters/etablissements.py
Reverts etalab/annuaire-entreprises-search-api#159
=> Revert "Retourner un champs vide pour `liste_enseignes` quand la liste est vide"

aio/aio-proxy/aio_proxy/response/formatters/enseignes.py, aio/aio-proxy/aio_proxy/response/formatters/etablissements.py
Reverts etalab/annuaire-entreprises-search-api#160
=> Revert "Revert "Retourner un champs vide pour `liste_enseignes` quand la liste est vide""

.github/workflows/workflow.yml, aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/main.py, aio/aio-proxy/aio_proxy/parsers/collectivite_territoriale.py
closes #126
closes #123
closes #120
=> Update swagger with etablissements data and Redoc support

aio/aio-proxy/aio_proxy/search/filters/boolean.py, aio/aio-proxy/aio_proxy/search/filters/nested_etablissements_filters.py, aio/aio-proxy/aio_proxy/search/filters/term_filters.py, aio/aio-proxy/aio_proxy/search/helpers/elastic_fields.py, aio/aio-proxy/aio_proxy/search/helpers/etablissements_filters_used.py, aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
=> Ajouter les établissements concernés par les filtres booléens de l'unité légale aux `matching_etablissements`

.github/workflows/workflow.yml
=> CI: update actions in CI workflow

aio/aio-proxy/aio_proxy/doc/open-api.yml
Fix some typing erros in API documentation.
=> docs: Fix typing issues

docker-compose-aio.yml
Add redis service to aio network in docker compose.
=> ops: add redis service to aio network

aio/aio-proxy/aio_proxy/routes.py
=> fix: remove sentry loggin level

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/format_search_results.py, aio/aio-proxy/aio_proxy/response/formatters/etablissements.py, aio/aio-proxy/aio_proxy/search/filters/nested_etablissements_filters.py, aio/aio-proxy/aio_proxy/search/geo_search.py, aio/aio-proxy/aio_proxy/search/helpers/elastic_fields.py, aio/aio-proxy/aio_proxy/search/helpers/etablissements_filters_used.py, aio/aio-proxy/aio_proxy/search/parameters.py, aio/aio-proxy/aio_proxy/search/text_search.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_bio.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_egapro.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_organisme_formation.py
- apply filter on statut_diffusion_unite_legale for each query
- format new data
=> Ajout données bio / uai / formation / statut_non_diffusion / slug / egapro

aio/aio-proxy/aio_proxy/parsers/page.py, aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
=> Handle error when page is higher than 1000

aio/aio-proxy/aio_proxy/search/geo_search.py, aio/aio-proxy/aio_proxy/search/parameters.py
Fixing missing param in geo search.
=> fix: add inclure slug param to geo search

aio/aio-proxy/aio_proxy/response/build_response.py
closes #225 
Testing integration on dev:
=> feat: capture all errors in sentry

aio/aio-proxy/aio_proxy/response/build_response.py, aio/aio-proxy/aio_proxy/routes.py
=> perf: group ValueError exceptions as Sentry warning

aio/aio-proxy/aio_proxy/response/format_search_results.py, aio/aio-proxy/aio_proxy/response/formatters/dirigeants.py, aio/aio-proxy/aio_proxy/response/formatters/etablissements.py, aio/aio-proxy/aio_proxy/response/formatters/non_diffusible.py, aio/aio-proxy/aio_proxy/search/geo_search.py, aio/aio-proxy/aio_proxy/search/text_search.py
* Using "NON-DIFFUSIBLE" mention instead of "ND"
* Filter non-diffusible before text search unless its a siren/siret search
* Hide all ND, including flux data
closes #233
closes https://github.com/etalab/annuaire-entreprises-search-infra/issues/156
=> Affichage des données non diffusible

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/parsers/categorie_entreprise.py, aio/aio-proxy/aio_proxy/search/parameters.py, aio/aio-proxy/aio_proxy/search/text_search.py, aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_categorie_entreprise.py
closes #235 
depends on https://github.com/etalab/annuaire-entreprises-search-infra/pull/159
related to https://github.com/etalab/annuaire-entreprises-site/issues/466
=> Ajouter le filtre `catégorie_entreprise`

aio/aio-proxy/aio_proxy/response/formatters/etablissements.py
=> fix: keep `liste_enseignes` type as an array in ND cases

aio/aio-proxy/aio_proxy/response/formatters/etablissements.py
=> fix: check if `list_enseignes` is empty for ND

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/format_search_results.py, aio/aio-proxy/aio_proxy/search/parameters.py, aio/aio-proxy/aio_proxy/search/text_search.py, pyproject.toml
=> Ajouter le filtre `est_qualiopi` et modifier les données organismes de formation

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/format_search_results.py
=> Ajouter `statut_diffusion` à la réponse d'API

aio/aio-proxy/requirements.pip
=> build(deps): upgrade requests dependency

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/format_search_results.py
=> feat: add year fields (categorie, tranche) to api paylaod

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/request/parsers/radius.py
=> Limit `near_point` radius to 50km

aio/aio-proxy/aio_proxy/labels/departements.json
closes #273 
depends on https://github.com/etalab/annuaire-entreprises-search-infra/pull/174
=> feat: add 975 to `departement` filter

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/format_search_results.py, aio/aio-proxy/aio_proxy/response/formatters/bilan_financier.py
=> Ajouter les données financières dans la réponse de l'API

aio/aio-proxy/aio_proxy/decorators/http_exception.py, aio/aio-proxy/aio_proxy/request/parsers/convention_collective.py, aio/aio-proxy/aio_proxy/request/search_params_builder.py, aio/aio-proxy/aio_proxy/response/format_search_results.py, aio/aio-proxy/aio_proxy/response/formatters/collectivite_territoriale.py, aio/aio-proxy/aio_proxy/response/formatters/selected_fields.py, aio/aio-proxy/aio_proxy/search/es_index.py, aio/aio-proxy/aio_proxy/search/es_search_runner.py, aio/aio-proxy/aio_proxy/search/filters/nested_etablissements_filters.py, aio/aio-proxy/aio_proxy/search/filters/siren.py, aio/aio-proxy/aio_proxy/search/filters/siret.py, aio/aio-proxy/aio_proxy/search/geo_search.py, aio/aio-proxy/aio_proxy/search/helpers/elastic_fields.py, aio/aio-proxy/aio_proxy/search/helpers/helpers.py, aio/aio-proxy/aio_proxy/search/queries/bilan.py, aio/aio-proxy/aio_proxy/search/queries/person.py, aio/aio-proxy/aio_proxy/search/queries/text.py, aio/aio-proxy/aio_proxy/search/text_search.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_activite_principale.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_categorie_entreprise.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_code_postal.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_tranche_effectif.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_type_personne.py, aio/aio-proxy/aio_proxy/utils/cache.py
related to https://github.com/etalab/annuaire-entreprises-search-infra/pull/181
=> chore: update elasticsearch functions with new index mapping

aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
=> Add some e2e tests use cases

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/formatters/etablissements.py, aio/aio-proxy/aio_proxy/response/unite_legale_model.py
closes #310 
depends on https://github.com/etalab/annuaire-entreprises-search-infra/pull/204
=> [Payload] feat: add fields `annee_tranche_effectif_salarie` and `date_mise_a_jour` in etablissements

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/formatters/dirigeants.py, aio/aio-proxy/aio_proxy/response/unite_legale_model.py, aio/aio-proxy/aio_proxy/search/text_search.py
closes #272 
depends on https://github.com/etalab/annuaire-entreprises-search-infra/pull/206
=> feat: update diriegeants fields

.github/workflows/workflow.yml, aio/aio-proxy/aio_proxy/response/metadata_endpoint/convention_collective.py, aio/aio-proxy/aio_proxy/routes.py, aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py, aio/aio-proxy/aio_proxy/utils/cache.py, aio/aio-proxy/aio_proxy/utils/helpers.py
closes #303 
depends on https://github.com/etalab/annuaire-entreprises-search-infra/pull/219
=> [METADATA][IDCC]feat: add endpoint that exposes `conventions collectives` metadata

aio/aio-proxy/aio_proxy/response/formatters/etablissements.py
=> feat: add `tranche_effectif_salarie_etablissement` and `annee_tranche_effectif_salarie_etablissement`

aio/aio-proxy/aio_proxy/response/formatters/elus.py, aio/aio-proxy/aio_proxy/tests/unit_tests/test_convert_date.py, aio/aio-proxy/aio_proxy/utils/helpers.py
closes https://github.com/etalab/annuaire-entreprises-site/issues/847
=> [BUG] Fix display date de naissance `élus` 

aio/aio-proxy/aio_proxy/response/format_search_results.py, aio/aio-proxy/aio_proxy/response/formatters/etablissements.py, aio/aio-proxy/aio_proxy/response/helpers.py, aio/aio-proxy/aio_proxy/response/unite_legale_model.py
related to https://github.com/etalab/annuaire-entreprises-search-api/issues/332
depends on https://github.com/etalab/annuaire-entreprises-search-infra/pull/254
This pull request brings changes to the payload by:
- Introducing `date_mise_a_jour_rne`: the date when data was modified in RNE.
- Introducing `date_mise_a_jour_insee`: the date when data was modified in SIRENE (INSEE).
- Adjusting `date_mise_a_jour` from the INSEE date to the date when data was indexed in Elasticsearch.
=> [PAYLOAD][RNE] Add minimal RNE siren data

aio/aio-proxy/aio_proxy/response/format_search_results.py, aio/aio-proxy/aio_proxy/response/formatters/etablissements.py, aio/aio-proxy/aio_proxy/response/formatters/nature_juridique.py, aio/aio-proxy/aio_proxy/response/unite_legale_model.py
* If `nature_juridique` is not in list of valid values, return `None`
* If `siege` does not exist, return `{} `instead of `None`
* Remove `date_mise_a_jour_rne` from `siege` object
=> [PAYLOAD]Clean RNE related fields in payload

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/format_search_results.py, aio/aio-proxy/aio_proxy/response/formatters/etablissements.py, aio/aio-proxy/aio_proxy/response/unite_legale_model.py
depends on https://github.com/etalab/annuaire-entreprises-search-infra/pull/266
related to https://github.com/etalab/annuaire-entreprises-search-infra/issues/217
=> [PAYLOAD]Add `date fermeture` for unité légale and établissement

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/request/field_values.py, aio/aio-proxy/aio_proxy/request/search_params_model.py, aio/aio-proxy/aio_proxy/response/formatters/etablissements.py, aio/aio-proxy/aio_proxy/response/unite_legale_model.py, aio/aio-proxy/aio_proxy/search/filters/nested_etablissements_filters.py, aio/aio-proxy/aio_proxy/search/helpers/etablissements_filters_used.py, aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
closes #https://github.com/etalab/annuaire-entreprises-search-api/issues/337
depends on https://github.com/etalab/annuaire-entreprises-search-infra/pull/269
=> [PAYLOAD][FILTERS]Add `EPCI` filter and field to payload

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/request/search_params_model.py, aio/aio-proxy/aio_proxy/response/formatters/complements.py, aio/aio-proxy/aio_proxy/response/unite_legale_model.py, aio/aio-proxy/aio_proxy/search/text_search.py, aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
closes #304 
depends on https://github.com/etalab/annuaire-entreprises-search-infra/pull/279
=> [PAYLOAD][FILTERS][SIAE]Add SIAE fields and filter to API

aio/aio-proxy/aio_proxy/utils/matomo.py
Reverts etalab/annuaire-entreprises-search-api#362
=> Revert "[MONITORING][MATOMO]feat: use ip address to id Matomo users"

.github/workflows/deploy.yml
Relates to : https://github.com/orgs/annuaire-entreprises-data-gouv-fr/projects/1?pane=issue&itemId=61469697#
=> chore: replace the deploy cmd

aio/aio-proxy/aio_proxy/request/field_values.py, aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
=> [BUG][GEOLOCALISATION]fix: increase allowed min radius value

aio/aio-proxy/aio_proxy/search/queries/text.py
=> [SEARCH]feat: lower threshold for inner hits

aio/aio-proxy/aio_proxy/tests/e2e_tests/response_tester.py, aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
* Add value tests for bool filters
* Test latitude and longitude values
=> [TESTING]Update e2e tests

aio/aio-proxy/aio_proxy/doc/open-api.yml
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/pull/351
Add precise description to geolocation fields.
=> [SWAGGER]docs: document geolocalisation process

aio/aio-proxy/aio_proxy/response/formatters/complements.py, aio/aio-proxy/aio_proxy/response/formatters/etablissements.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/pull/356
=> [CHORE]chore: update idcc var name

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/formatters/etablissements.py, aio/aio-proxy/aio_proxy/response/unite_legale_model.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/271
depends on https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/pull/367
=> [PAYLOAD]feat: add ancien_siege field to etab object

aio/aio-proxy/aio_proxy/doc/open-api.yml, aio/aio-proxy/aio_proxy/response/format_search_results.py, aio/aio-proxy/aio_proxy/response/formatters/nom_complet.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1163
=> [PAYLOAD]Use `nom commercial` (siege) in ul `nom complet`

aio/aio-proxy/aio_proxy/response/format_search_results.py, aio/aio-proxy/aio_proxy/response/formatters/nom_complet.py, aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-api/pull/403
=> [BUG]fix: get nom commercial in case of missing siege

.github/workflows/workflow.yml, app/config.py, app/logging.py, app/main.py, app/requirements.pip, app/service/convention_collective.py, app/utils/helpers.py, app/utils/matomo.py, app/utils/redis.py
closes #413 
depends on https://github.com/annuaire-entreprises-data-gouv-fr/infrastructure/pull/205
=> [CORE]Handle general settings using pydantic-settings

app/service/formatters/nom_complet.py, app/tests/e2e_tests/test_api.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1228#issuecomment-2384854677
=> [FIX]Remove denomination usuelle from nom complet in case of error

app/elastic/es_search_runner.py, app/elastic/helpers/helpers.py
closes https://github.com/annuaire-entreprises-data-gouv-fr/search-api/issues/429
=> [CACHE]feat: cache siren and siret queries

app/tests/e2e_tests/test_api.py
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/pull/473
=> [CHORE]tests: update e2e

.github/workflows/workflow.yml, app/utils/helpers.py
=> [UPDATE]deps: upgrade Python

app/requirements.txt
https://errors.data.gouv.fr/organizations/sentry/issues/248834/?project=14&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h
=> fix(elastic): downgrade due to pagination issues

app/controller/search_params_model.py, app/doc/open-api.yml, app/elastic/text_search.py, app/models/unite_legale.py, app/service/formatters/complements.py, app/tests/e2e_tests/test_api.py
=> [Payload][Filter]Add `est_l100_3` filter and field

app/main.py
Reverts annuaire-entreprises-data-gouv-fr/search-api#481
=> Revert "[TMP]fix(apm): deactivate apm due to sentry errors"

app/doc/open-api.yml
related https://www.data.gouv.fr/fr/dataservices/api-recherche-dentreprises/?mtm_campaign=mail-datagouv#discussion-67ef9508299edaa81738fa51
=> [SWAGGER]docs: update param description

app/controller/search_params_model.py, app/doc/open-api.yml, app/elastic/text_search.py, app/models/unite_legale.py, app/service/formatters/complements.py, app/tests/e2e_tests/test_api.py, pyproject.toml
Related to https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/495
=> Add est_achats_responsables filter

app/controller/search_params_model.py, app/doc/open-api.yml, app/elastic/text_search.py, app/models/unite_legale.py, app/service/formatters/complements.py, app/tests/e2e_tests/test_api.py
depends on https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/pull/511
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-api/issues/477
=> [NEW-DATA]Add patrimoine vivant filter and field

.github/workflows/workflow.yml
The label:
With the label:
Without the label:
=> ci: use label to choose elastic env

app/controller/search_params_model.py, app/doc/open-api.yml, app/elastic/text_search.py, app/models/unite_legale.py, app/service/formatters/complements.py, app/tests/e2e_tests/test_api.py
Related to https://github.com/annuaire-entreprises-data-gouv-fr/search-api/issues/510
=> Add est_alim_confiance to api

app/doc/open-api.yml, app/models/unite_legale.py, app/service/formatters/complements.py, app/tests/e2e_tests/test_api.py
closes #525 
depends on https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/pull/538
=> [New field]add `bilan_ges_renseigne` to complements object

app/requirements.txt
closes https://github.com/annuaire-entreprises-data-gouv-fr/search-api/pull/527
=> [Dependencies]chore: update packages

app/requirements.txt
* sentry-sdk
* pydantic-settings
=> [Dependencies]deps: update packages

app/tests/e2e_tests/test_api.py
related to https://github.com/etalab/annuaire-entreprises-search-api/pull/357
=> [CHORE] Activate `societe a mission` test
