annuaire-entreprises-data-gouv-fr/search-api

- aio/aio-proxy/aio_proxy/response.py
- aio/aio-proxy/aio_proxy/search/helpers.py
- aio/aio-proxy/aio_proxy/search/search_functions.py
closes #22 
* Change response variable names to be more accurate
* Change response format to dict instead of array
* Remove useless variables from response
> Format API response

- aio/aio-proxy/aio_proxy/response/format_response.py
Error: API returns null values for all fields.
> Fix: add return keyword to get_field function

- aio/aio-proxy/aio_proxy/doc/open-api.yml
- aio/aio-proxy/aio_proxy/labels/helpers.py
- aio/aio-proxy/aio_proxy/labels/sections-codes-NAF.json
- aio/aio-proxy/aio_proxy/parsers/section_activite_principale.py
- aio/aio-proxy/aio_proxy/response/format_response.py
- aio/aio-proxy/aio_proxy/response/parameters.py
- aio/aio-proxy/aio_proxy/tests/test_section_activite_principale.py
closes #34 
depends on https://github.com/etalab/data-engineering-stack/pull/15
depends on https://github.com/etalab/annuaire-entreprises-search-infra/pull/15
👉 **SIDE NOTE**: 
I could not find a way to use enum with named items for `section_activite_principale` parameter in swagger.
Consequently, I added corresponding descriptions in parameter description instead. 
Issues discussing this : 
https://github.com/OAI/OpenAPI-Specification/issues/681
https://github.com/json-schema-org/json-schema-spec/issues/1062
https://github.com/json-schema-org/json-schema-spec/issues/57
> Add 'section activaté principle' filter to API

- aio/aio-proxy/aio_proxy/routes.py
I dont have API locally installed so I let @geoffreyaldebert try it.
I followed the sentry documentation to log 10% of API call : 
https://docs.sentry.io/platforms/python/guides/aiohttp/
And use a generic grouping of transactions by route :
https://docs.sentry.io/platforms/python/guides/aiohttp/#options
> Add APM support in sentry

- docker-compose-elastic.yml
Desperate times calls for desperate measures...
I need to merge this, otherwise I won't be able to index in staging for performance tests tomorrow 😬
Once again the E2E tests rely on `dev` indices to test the API, and since the indices in the dev are currently the `établissements` ones , the tests logically do not pass.
Once the `établissements` search PR is merged, this problem will be solved for the following PRs.
> ops: increase elasticsearch jvm memory to 8g

- aio/aio-proxy/aio_proxy/search/filters/nested_etablissements_filters.py
Error when using only a filter in request
> fix: add missing letter to nested filter

- aio/aio-proxy/aio_proxy/response/format_search_results.py
- aio/aio-proxy/aio_proxy/response/formatters/enseignes.py
- aio/aio-proxy/aio_proxy/response/formatters/etablissements.py
closes #144 
related to #115 
Hide some fields in returned `établissements` object like detailed address fields, dates etc to make the response more compact and concise.
> Format la réponse API (les établissements)

- aio/aio-proxy/aio_proxy/search/execute_search.py
- aio/aio-proxy/aio_proxy/search/queries/text.py
closes #148 
Use `collapse` option in Elasticsearch to group results, containing the same `unité légale` with different établissements, by `siren`.
Also, awe increase the number of inner hits returned from the default 3 to 10.
> feat: group search results by siren

- aio/aio-proxy/aio_proxy/search/execute_search.py
- aio/aio-proxy/aio_proxy/search/filters/nested_etablissements_filters.py
- aio/aio-proxy/aio_proxy/search/queries/text.py
When using filters, no specific sorting method was used. Hence, the results appeared to be random and often the top results are inactive `unites légales`.
To fix this, we sort on `nombre établissements ouverts` when only filters are used (without text search).
Also, this PR increases the size of `matching établissements` (inner hits) from the default `3` to `10`, similar to what was done with text search.
> Trier par `nombre établissements ouverts` quand uniquement des filtres sont utilisés

- aio/aio-proxy/aio_proxy/parsers/string_parser.py
- aio/aio-proxy/aio_proxy/parsers/terms.py
When searching for terms using upper case terms and when searching using the same terms but in lower case, the results are different. Fix the terms parsing by use lower case by default.
> Fix case sensitive terms match

- aio/aio-proxy/aio_proxy/response/formatters/enseignes.py
- aio/aio-proxy/aio_proxy/response/formatters/etablissements.py
Return an empty field instead of an empty list for `enseignes`, and rename it to `liste_enseignes` to maintain consistency with other list fields.
> Retourner un champs vide pour `liste_enseignes` quand la liste est vide

- aio/aio-proxy/aio_proxy/doc/open-api.yml
- aio/aio-proxy/aio_proxy/response/formatters/etablissements.py
- aio/aio-proxy/aio_proxy/search/queries/text.py
The address now used `code_postal` instead of `code_commune`. We should however be able to find the `établissement` using `code_commune` as well. Hence, we add the field to the multi-match search.
> Add `commune` to multi-match search

- aio/aio-proxy/aio_proxy/parsers/per_page.py
- aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
A call with `per_page=0` caused an internal server error report.
> fix: cover nil per page

- aio/aio-proxy/aio_proxy/response/helpers.py
- aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
Some siren have empty `nom_complet` (example: `337698138` https://annuaire-entreprises.data.gouv.fr/entreprise/337698138?redirected=1), it causes an internal server error because we did not cover that possibility.
> fix: return `None` when `nom_complet` is empty

- aio/aio-proxy/aio_proxy/search/queries/text.py
The search text query uses the wrong elastic search field names `denomination_usuelle_1` instead of `denomination_usuelle_1_unite_legale`.
> fix: rectify denomination usuelle field names in text query search

- aio/aio-proxy/aio_proxy/parsers/ban_params.py
- aio/aio-proxy/aio_proxy/search/parameters.py
- aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
Many calls have been made to the API using a `localisation` parameter (which does not exist) with some filters. These calls are very heavy and have caused multiple timeouts today.
This PR send a `400` response when making a request with a `localisation` param.
> feat: add ban parameters function to parameter parsing

- .github/workflows/workflow.yml
- aio/Dockerfile
- aio/aio-proxy/requirements.pip
Conflicts with aiohttp and redis when using python `3.11.2`, downgrading for now...
> Downgrade python version from 3.11 to 3.10

- aio/aio-proxy/aio_proxy/search/execute_search.py
When elastic search offset and page size was moved to the execute search function (to avoid unnecessary aggregation by siren), it was no longer part of the `search` object which we use as cache key.
This PR adds the offset' and page size to the search object before caching it.
> fix: add page and page size to cache key

- aio/aio-proxy/aio_proxy/doc/open-api.yml
- aio/aio-proxy/aio_proxy/parsers/int_parser.py
- aio/aio-proxy/aio_proxy/response/format_search_results.py
- aio/aio-proxy/aio_proxy/response/formatters/bilan_financier.py
- aio/aio-proxy/aio_proxy/search/filters/boolean.py
- aio/aio-proxy/aio_proxy/search/helpers/bilan_filters_used.py
- aio/aio-proxy/aio_proxy/search/helpers/elastic_fields.py
- aio/aio-proxy/aio_proxy/search/parameters.py
- aio/aio-proxy/aio_proxy/search/queries/bilan.py
- aio/aio-proxy/aio_proxy/search/text_search.py
5 new filters : 
- `bilan_renseigne` # true or false
- `ca_min` and `ca_max` # allows to filter between range of chiffre d'affaire of a company
- `resultat_net_min` and `resultat_net_max` # allows to filter between range of resultat net of a company
New properties added in response : 
In `complements` : `bilan_renseigne` # Indicate if a bilan exist for a specific company
In payload `bilan_financier`. When fulfilled three properties : 
```
"bilan_financier": {
"ca": 1379705,
"resultat_net": 321178,
"date_cloture_exercice": "2021-12-31"
},
```
> Add bilan_financier object in API

- aio/aio-proxy/aio_proxy/doc/open-api.yml
- aio/aio-proxy/aio_proxy/response/format_search_results.py
Due to inconsistencies in financial data and awaiting quality improvement, we hide temporarily financial data in API payload.
> Hide `données financières` in API payload

- aio/aio-proxy/aio_proxy/doc/open-api.yml
The link used in swagger if outdated.
> fix: correct `est_service_public` permalink

- aio/aio-proxy/aio_proxy/response/format_search_results.py
- aio/aio-proxy/aio_proxy/search/text_search.py
`est_qualiopi=false` and `est_entrepreneur_spectacle=false`  :  return no results because the data indexed is either `True` or `None`.  The API shows the `None` as `False` (because we format the fields), however the `None` values cannot be filtered when using `False` as the bool filter 's value. 
This issue is resolved once the indexed value `None` is replaced with `False`
https://github.com/etalab/annuaire-entreprises-search-infra/pull/167
`egapro_renseignee=false`: works fine now because it was using a bool filter in the search function instead of a term filter like the other fields (happy coincidence maybe 🤷). 
However, once the aforementioned change in indexing the bool values takes place, this filter will no longer return any results. In order to fix that, the `egapro_renseignee` …
> Fix empty payload when bool filter equals `False`

- aio/aio-proxy/aio_proxy/request/search_params_builder.py
- aio/aio-proxy/aio_proxy/request/search_params_model.py
- aio/aio-proxy/aio_proxy/response/format_search_results.py
depends on https://github.com/etalab/annuaire-entreprises-search-api/pull/281
These filters are now included in `include` parameter.
> [REFACTOR] Remove `inclure_slug` and `inclure_score` parameters

- aio/aio-proxy/aio_proxy/search/filters/siret.py
Siret search returns no resutls because path was missing `unite legale` object.
> fix: add unite legale to siret path

- aio/aio-proxy/aio_proxy/search/helpers/helpers.py
`liste_idcc` and `cedex` fields returned as strings in payload in object `matching_etablissements`.
`matching_etablissements` is returned as an Elasticsearch `AttrDict` and not as a Python Dict which makes accessing attributes more tricky. We cast the object as a Python dict to avoid errors.
> fix: convert es matching etablissement to list

- aio/aio-proxy/aio_proxy/request/parsers/int_parser.py
API reutrn this error if int is bigger than Elasticsearch `long` type : 
`RequestError(400, 'search_phase_execution_exception', 'failed to create query: Value [[31 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30]] is out of range for a long')"`
This PR handles this error by returning a 400 with details if given number is outside expected range.
> fix: return 400 if `int` is bigger than ES long range

- aio/aio-proxy/aio_proxy/request/parsers/latitude.py
- aio/aio-proxy/aio_proxy/request/parsers/longitude.py
- aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
Error detected in Sentry : `RequestError(400, 'x_content_parse_exception', '[1:254] [bool] failed to parse field [filter]')` when calling `near_point?lat=nan&long=nan`.
`float()` was used to validate `lat` and `long` parameters in request. 
Python has a built-in representation for NaN as a floating-point value. In Python, float("nan") will simply create a floating-point NaN value rather than raising an error. So when `nan` values are given (example `lat=nan`), they are validated without raising an error, and are given to Elasticsearch which in return raises that above-mentioned error.
This PR adds the `nan` value handling to the parsing and validation functions.
> Latitude and longitude parse NaN values as floats

- aio/aio-proxy/aio_proxy/request/search_params_builder.py
- aio/aio-proxy/aio_proxy/request/search_params_model.py
- aio/aio-proxy/aio_proxy/search/geo_search.py
- aio/aio-proxy/aio_proxy/search/helpers/exclude_etablissements.py
- aio/aio-proxy/aio_proxy/search/text_search.py
Post factorosation the site has completely migrated to using new inclusion parameters. The `inclure_etablissements` param is no longer used.
> Remove `inclure etablissements` parameter

- aio/aio-proxy/aio_proxy/request/helpers.py
- aio/aio-proxy/aio_proxy/request/search_params_builder.py
Error captured in Sentry `RequestError(400, 'search_phase_execution_exception', 'Result window is too large, from + size must be less than or equal to: [10000] but was [10025]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.')`.
So far, Exception handler only captured the error when page is higher than 1000. However, when `per_page`  is bigger than 10, the 10.000 limit (number of results in ES) is reached before the page reaches 1000.
Henceforth the rule is `page*per_page` should be lower `10.000`.
> fix: add 400 error message when `page*per_page` is bigger than 10 000

- aio/aio-proxy/aio_proxy/decorators/http_exception.py
- aio/aio-proxy/aio_proxy/search/es_search_runner.py
Some queries are experiencing long response times, often exceeding 5 seconds, particularly for simple queries such as `rue` and `rue des`. These extended query durations lead to notable delays for other queries and, at times, result in the API becoming unresponsive. This pull request addresses this issue by implementing a 1-second query timeout. When a query surpasses this threshold, the API will respond with a 504 error message, and the associated error will be logged in Sentry.
> [Performance] Add ES query timeout

- aio/aio-proxy/aio_proxy/doc/open-api.yml
- aio/aio-proxy/aio_proxy/request/search_params_builder.py
- aio/aio-proxy/aio_proxy/request/search_params_model.py
- aio/aio-proxy/aio_proxy/response/formatters/complements.py
- aio/aio-proxy/aio_proxy/search/text_search.py
depends on #https://github.com/etalab/annuaire-entreprises-search-infra/pull/216
closes #270 
**⚠️ TBD**
Are we expected to include the `economie_sociale_solidaire_unite_legale` field in the output, alongside `est_ess`, to enable the website to issue a warning in the event of inconsistency? @XavierJp 
🟢 **Update:** `est_ess` is now the union of `est_ess_france` and `economie_sociale_solidaire_unite_legale`.
> [DATA][ESS]feat: use new field `est_ess` union of ESS France and INSEE

- aio/aio-proxy/aio_proxy/doc/open-api.yml
User sent an email to let us know the new added fields to api payload are not included in swagger.
> [SWAGGER]docs: add missing fields

- aio/aio-proxy/aio_proxy/response/build_api_response.py
- aio/aio-proxy/aio_proxy/utils/matomo.py
closes #324 
This PR introduces Matomo tracking code. Now, API calls will be tracked with a probability of 1 in 1000, providing a sampling mechanism for Matomo tracking.
depends on https://github.com/etalab/annuaire-entreprises-infrastructure/pull/32
> [MONITORING]feat: track api calls via Matomo

- .github/workflows/deploy.yml
Relates to :
- https://github.com/etalab/annuaire-entreprises-site/pull/929
- https://github.com/etalab/annuaire-entreprises-infrastructure/pull/84
---
Up until now, when an error occured during the deployment, it was not reported in the Github action. This was due to the presence of the pipe that was sending both the stdout & the stderr to the tee command.
---
expected : 
```
/usr/bin/docker
success
```
actual : 
```
/usr/bin/docker
success
```
```sh
ssh annuaire-entreprises-staging-www-1 'which docker | tee --append /tmp/debug_err' && echo 'success' || echo 'error' 
```
---
expected : 
```
/usr/bin/docker
success
```
actual : 
```
/usr/bin/docker
success
```
```sh
ssh annuaire-entreprises-staging-www-1 'which docker 1> >(tee --append /tmp/debug_err)' && echo 'success' || echo 'error' …
```
> chore: the SSH command exit status is always forwarded to the executor

- aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
related to https://github.com/etalab/annuaire-entreprises-search-infra/pull/306
INSEE stock data has issues and `societe_a_mission` field is always null.
> [BUG]fix: deactivate societe a mission e2e test

- aio/aio-proxy/aio_proxy/request/search_params_model.py
- aio/aio-proxy/aio_proxy/search/helpers/helpers.py
- aio/aio-proxy/aio_proxy/search/queries/text.py
- aio/aio-proxy/aio_proxy/search/text_search.py
Closes #340
A new search option has been added, introducing changes to the search algorithm that prioritize larger companies in the search results.
The field used to weight the search results is `facteur_taille_entreprise`, calculated as the product of two fields: `code_categorie_entreprise` and `nombre_etablissements_ouverts`.
To emphasize larger companies, a new parameter, `sort_by_size`, has been introduced. This parameter accepts a boolean value of True or False.
> [PARAMETERS]feat: add sort_by_size param to request

- app/main.py
This is by default the behaviour in fastAPI, however the last exception handler by default returns a 404 for unknown endpoints.
> [FIX]Add redoc url redirect `/docs to /docs/`

- app/doc/open-api.yml
Recent updates to the Swagger documentation were overlooked during the migration to FastAPI; this PR reintroduces those changes.
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-api/pull/417
> [CHORE]docs: add missing fields to swagger

- app/models/unite_legale.py
- app/service/formatters/immatriculation.py
- app/tests/e2e_tests/test_api.py
When `immatriculation` is `null`, typically for non-diffusible items, the API returns an error because `None` is not considered a valid value in the Pydantic model for this object. This PR introduces support for the `None` option. Additionally, "La Poste" is missing from the RNE stock, resulting in an empty `immatriculation` object and a `null` value for `date_mise_a_jour_rne`. This causes the end-to-end tests to fail, as "La Poste" is used in many test cases.
> [BUG]fix(response): return empty dict if immat is null

- app/elastic/queries/person.py
closes https://github.com/annuaire-entreprises-data-gouv-fr/search-api/issues/374
The filters for `nom_personne` and `prenoms_personne` currently use two types of queries. The first is a `match` query, which ensures that each word in the query is present in the results. The second is a `match_phrase` query, which boosts the score for exact matches, ensuring those results are prioritized.
However, when handling names like **"BERNARD DE SAINT AFFRIQUE"**, which contain French stop words (e.g., **"DE"**), the `match` query fails. This happens because the custom analyzer used during indexing removes stop words like "DE", meaning no match is found for them. While the `match_phrase` still correctly identifies exact matches, the `must` clause of the `match` query returns no results due to the …
> [SEARCH]fix: remove stop words from dirigeant before match query

- app/controller/search_params_model.py
An HTTP 500 error is generated when the "radius" field is not a number.
Example:
http://recherche-entreprises.api.gouv.fr/near_point?minimal=true&include=siege,matching_etablissements&lat=47.92139251962604&long=-1.9418394282147005&radius=NaN&per_page=25&page=1
**Fix**: Add a check to validate if "radius" lower case  is not a number (`nan`) and raise a `ValueError` in such cases. This will ensure the API properly handles invalid inputs and returns a more appropriate error message instead of an HTTP 500.
> [FIX]Raise error if radius is nan

- app/elastic/parsers/siren.py
- app/elastic/parsers/siret.py
- app/tests/unit_tests/test_siren.py
- app/tests/unit_tests/test_siret.py
closes https://github.com/annuaire-entreprises-data-gouv-fr/homologation/issues/13
Replace regular expressions which validate siren and siret with more restrictive expressions.
Add unit tests for both functions.
> [SECURITY]Implement EY recommendations

- app/controller/search_params_builder.py
- app/controller/search_params_model.py
- app/tests/e2e_tests/test_api.py
In Sentry, an error occurred while using the `near_point?radius=10` query. This was because the `lat` and `long` parameters were made mandatory when either of them was provided, but they were not set as obligatory for the endpoint itself. 
Another issue identified was the possibility of scraping data by combining the `lat`, `long`, and `radius` parameters with the `page` parameter in the `/search` endpoint. The API treated these parameters as valid inputs without restricting their use, allowing users to theoretically navigate through pages. This PR resolves these issues by clearly defining which primary parameters are required for each endpoint.
> [BUG]fix: add search type validation for certain params

- app/controller/search_params_model.py
- app/tests/e2e_tests/test_api.py
When given a string value for param `ca_min` for example, it returns a 500 instead of Bad Request.
> [BUG][SENTRY]Add type validation to financial params

- app/routers/public.py
- app/tests/e2e_tests/response_tester.py
- app/tests/e2e_tests/test_api.py
Added a simple endpoint that returns a 204 No Content response for `/favicon.ico` requests. This is a minimal implementation that:
- Eliminates 404 errors from logs
- Doesn't waste resources serving an actual favicon (since this is an API service)
- Properly handles the browser requests without affecting API functionality
- Verified that browser requests for favicon.ico now return 204 instead of 404
- Confirmed logs no longer show 404 errors for favicon requests
Very cryptic warning in Sentry, might be related to this. We'll see 👀
> fix: add favicon endpoint to handle browser requests

- app/elastic/queries/text.py
[USER FEEDBACK]
This addresses an issue where the query `/search?q=maccity&code_postal=31000` returns an empty list, while `/search?q=maccity `correctly retrieves an unite legale that has an associated etablissement in the 31000 postal code. The reason for the discrepancy lies in the scoring: the text query's score was 2.08, which fell below the threshold of 3, resulting in no results being returned.
To resolve this, the PR lowers the threshold from 3 to 2. While this change may potentially introduce the risk of including more results when querying the API, the thresholds were originally determined through trial and error rather than a rigorous benchmark. Additionally, the test set used at the time has since become outdated.
> feat(search algo): decrease threshold score for matching etab

- app/requirements.txt
related to https://github.com/annuaire-entreprises-data-gouv-fr/search-api/issues/121
All E2E tests pass for this update 🤞
> [OPS]deps(build): upgrade to Elasticsearch 8.17

- app/requirements.txt
This PR updates FastAPI.
There are no breaking changes for us since we don't use any streaming behavior. I tested it locally and didn’t observe any issues — response times might be slightly laggy, but that could just be due to my spotty internet this morning.
To be safe, I’ll go ahead and merge it.
@PaulLesur — could you deploy it tomorrow morning and keep an eye on response times, just in case?
Thanks!
> [Maintenance]deps: update packages

- app/service/formatters/non_diffusible.py
- app/tests/e2e_tests/test_api.py
related to #567 
@hacherix you were right, l'Insee treats le siege and the other etablissements the same way according to their API.
> 🔒 [DataPrivacy]fix(nd): show denimination fields for etablissements nd
